# Coding and Programming

## Capítulo 7

### Procesamiento de datos, estadísticas descriptivas y visualización de datos

- **Unidad 34.** Uso de módulos de Python
- **Unidad 35.** Serie de Pandas para el tratamiento de datos
- **Unidad 36.** Pandas DataFrame para procesamiento de datos
- **Unidad 37.** Ordenamiento de datos
- **Unidad 38.** Datos de series temporales

___

## Q 34-01

Convierta los siguientes datos del diccionario en un dataframe usando **Pandas**.

(Denomina el dataframe `df`)

`d = { 'col1':[1,2], 'col2':[3,4], 'col3':[5,6], 'col4':[7,8] }`

In [ ]:
import pandas as pd

d = { 'col1':[1,2], 'col2':[3,4], 'col3':[5,6], 'col4':[7,8] }

df = pd.DataFrame(data = d)

df

   col1  col2  col3  col4
0     1     3     5     7
1     2     4     6     8

___

## Q 35-01

En el marco de datos creado en la pregunta **Q 34-01**, cree un nuevo dataframe que consista solo en los datos de la columna con el nombre de columna `'col4'`.

(Denomina el dataframe `new_df`)

In [ ]:
new_df = pd.DataFrame(data = df['col4'])

new_df

   col4
0     7
1     8

___

## Q 36-01

El índice del dataframe creado en la pregunta **Q 34-01** es `0` y `1`.

Escriba un comando para cambiar el nombre de estos índices a `primero` y `segundo`.

In [ ]:
df.rename(index={0:"Primero", 1:"Segundo"}, inplace=True)

df

         col1  col2  col3  col4
Primero     1     3     5     7
Segundo     2     4     6     8

___

## Q 37-01

Escriba un comando para buscar datos faltantes en el dataframe `df` creado en la pregunta **Q 34-01** e imprima el resultado.

(Sin embargo, los datos que faltan deben devolverse como verdaderos).

In [ ]:
df.isnull()

          col1   col2   col3   col4
Primero  False  False  False  False
Segundo  False  False  False  False

___

## Q 38-01

Escriba un comando para verificar el resumen de las estadísticas descriptivas (desviación estándar, valor mínimo, moda, etc.) del dataframe `df` creado en la pregunta **Q 34-01** e imprima el resultado.

In [ ]:
df.describe()

           col1      col2      col3      col4
count  2.000000  2.000000  2.000000  2.000000
mean   1.500000  3.500000  5.500000  7.500000
std    0.707107  0.707107  0.707107  0.707107
min    1.000000  3.000000  5.000000  7.000000
25%    1.250000  3.250000  5.250000  7.250000
50%    1.500000  3.500000  5.500000  7.500000
75%    1.750000  3.750000  5.750000  7.750000
max    2.000000  4.000000  6.000000  8.000000

___

# Fin